import { requireSession, serverError } from "../../../../lib/serverAuth";
import { isPrimaryAdministrator, requirePortalResource } from "../../../../lib/portalVisibility";
import { compactAuditRecord, recordAudit } from "../../../../lib/auditLog";

const text = (value, maximum = 5000) => { const clean = String(value || "").trim(); return clean ? clean.slice(0, maximum) : null; };
const amount = (value) => value === "" || value == null ? null : (Number.isFinite(Number(value)) && Number(value) >= 0 ? Number(value) : null);
async function primary(access, resource) { if (!access.isAdmin || !isPrimaryAdministrator(access)) return Response.json({ error: "This restricted workflow is available only to the designated primary administrators." }, { status: 403 }); return requirePortalResource(access, resource); }

export async function GET(request) {
  try { const access = await requireSession(request); if (access.error) return access.error; const mode = new URL(request.url).searchParams.get("mode"); const resource = mode === "margins" ? "admin.portal_management.commercial_margins" : "admin.portal_management.psychosocial"; const denied = await primary(access, resource); if (denied) return denied;
    if (mode === "margins") { const [{ data: margins, error }, { data: projects }] = await Promise.all([access.admin.from("commercial_margin_snapshots").select("id, project_id, approved_revenue, reconciled_actual_cost, margin_amount, margin_percent, source_note, status, locked, approved_by, approved_at, created_at, updated_at").order("updated_at", { ascending: false }), access.admin.from("projects").select("id,name,status").neq("status", "archived").order("name")]); if (error) return Response.json({ error: error.message }, { status: 400 }); return Response.json({ margins: margins || [], projects: projects || [] }); }
    const { data, error } = await access.admin.from("psychosocial_support_cases").select("id, created_by, status, urgency, preferred_contact, confidential_summary, assigned_reviewer, submitted_at, triaged_at, closed_at, retention_review_at, locked, created_at, updated_at").order("updated_at", { ascending: false }).limit(150); if (error) return Response.json({ error: error.message }, { status: 400 }); return Response.json({ cases: data || [] });
  } catch (error) { return serverError(error); }
}

export async function POST(request) {
  try { const access = await requireSession(request); if (access.error) return access.error; const body = await request.json(); if (body.mode !== "margins") return Response.json({ error: "Unsupported restricted workflow." }, { status: 400 }); const denied = await primary(access, "admin.portal_management.commercial_margins"); if (denied) return denied; if (!body.projectId) return Response.json({ error: "Choose a project." }, { status: 400 }); const revenue = amount(body.approvedRevenue); const cost = amount(body.reconciledActualCost); if (revenue == null || cost == null) return Response.json({ error: "Approved revenue and reconciled actual cost are required." }, { status: 400 }); const marginAmount = revenue - cost; const marginPercent = revenue ? Number(((marginAmount / revenue) * 100).toFixed(2)) : null; const { data, error } = await access.admin.from("commercial_margin_snapshots").upsert({ project_id: body.projectId, approved_revenue: revenue, reconciled_actual_cost: cost, margin_amount: marginAmount, margin_percent: marginPercent, source_note: text(body.sourceNote, 3000), status: "draft", created_by: access.user.id, updated_by: access.user.id, updated_at: new Date().toISOString() }, { onConflict: "project_id" }).select().single(); if (error) return Response.json({ error: error.message }, { status: 400 }); await recordAudit(access.admin, { actorId: access.user.id, action: "saved", entityType: "commercial_margin_snapshot", entityId: data.id, projectId: data.project_id, resourceKey: "admin.portal_management.commercial_margins", afterData: compactAuditRecord(data, ["project_id", "status", "locked"]), reason: data.source_note }); return Response.json({ margin: data }, { status: 201 });
  } catch (error) { return serverError(error); }
}

export async function PATCH(request) {
  try { const access = await requireSession(request); if (access.error) return access.error; const body = await request.json(); const mode = body.mode; const resource = mode === "margins" ? "admin.portal_management.commercial_margins" : "admin.portal_management.psychosocial"; const denied = await primary(access, resource); if (denied) return denied; const now = new Date().toISOString();
    if (mode === "margins") { const { data: current, error: readError } = await access.admin.from("commercial_margin_snapshots").select("*").eq("id", body.id).single(); if (readError) return Response.json({ error: "Margin snapshot not found." }, { status: 404 }); if (current.locked && body.action !== "unlock") return Response.json({ error: "This margin snapshot is locked." }, { status: 409 }); const values = { updated_by: access.user.id, updated_at: now }; if (body.action === "review") values.status = "review"; if (body.action === "approve") { values.status = "approved"; values.approved_by = access.user.id; values.approved_at = now; values.locked = true; } if (body.action === "archive") { values.status = "archived"; values.locked = true; } if (body.action === "unlock") { if (!text(body.reason, 1000)) return Response.json({ error: "Provide an unlock reason." }, { status: 400 }); values.locked = false; } const { data, error } = await access.admin.from("commercial_margin_snapshots").update(values).eq("id", current.id).select().single(); if (error) return Response.json({ error: error.message }, { status: 400 }); await recordAudit(access.admin, { actorId: access.user.id, action: body.action || "updated", entityType: "commercial_margin_snapshot", entityId: data.id, projectId: data.project_id, resourceKey: resource, beforeData: compactAuditRecord(current, ["status", "locked"]), afterData: compactAuditRecord(data, ["status", "locked"]), reason: text(body.reason, 1000) }); return Response.json({ margin: data }); }
    const { data: current, error: readError } = await access.admin.from("psychosocial_support_cases").select("*").eq("id", body.id).single(); if (readError) return Response.json({ error: "Support case not found." }, { status: 404 }); if (current.locked && body.action !== "unlock") return Response.json({ error: "This support case is locked." }, { status: 409 }); if (!["triage", "action", "close", "archive", "unlock", "lock"].includes(body.action)) return Response.json({ error: "Choose a valid support-case action." }, { status: 400 }); const values = { updated_at: now }; if (body.action === "triage") { values.status = "triaged"; values.triaged_at = now; values.assigned_reviewer = body.assignedReviewer || access.user.id; } if (body.action === "action") values.status = "actioned"; if (body.action === "close") { values.status = "closed"; values.closed_at = now; values.locked = true; } if (body.action === "archive") { values.status = "archived"; values.locked = true; } if (body.action === "lock") values.locked = true; if (body.action === "unlock") { if (!text(body.reason, 1000)) return Response.json({ error: "Provide an unlock reason." }, { status: 400 }); values.locked = false; } const { data, error } = await access.admin.from("psychosocial_support_cases").update(values).eq("id", current.id).select("id,status,urgency,assigned_reviewer,retention_review_at,locked,updated_at").single(); if (error) return Response.json({ error: error.message }, { status: 400 }); await access.admin.from("psychosocial_case_access_log").insert({ case_id: current.id, actor_id: access.user.id, action: body.action }); await recordAudit(access.admin, { actorId: access.user.id, action: body.action, entityType: "psychosocial_support_case", entityId: data.id, resourceKey: resource, beforeData: compactAuditRecord(current, ["status", "locked"]), afterData: compactAuditRecord(data, ["status", "locked"]), reason: text(body.reason, 1000) }); return Response.json({ case: data });
  } catch (error) { return serverError(error); }
}
