import { useState } from "react";
import { CheckCircle2, Download, FileSpreadsheet, ShieldAlert } from "lucide-react";
import { useAuth } from "../lib/AuthProvider";

const DATASETS = [
  ["projects", "Project Register", "Active and historical project records."],
  ["activities", "Project Activities", "Project-scoped work activities and progress."],
  ["schedule", "Project Schedule / Gantt", "Project-scoped schedule lines and dates."],
  ["allocations", "Project Allocations", "Allocated staff and hours."],
  ["service_requests", "Service Requests", "Operational request register."],
  ["whs_forms", "WHS / EC Form Register", "Compliance submission register."],
  ["closeouts", "Project Close-Out Register", "Close-out outcomes and lessons."],
  ["improvements", "Improvement Actions", "Actions generated from close-outs."],
  ["regulatory_sources", "Regulatory Source Health", "Official source configuration and scan health."],
];

export default function AdminExportCentre() {
  const { session } = useAuth();
  const [dataset, setDataset] = useState("projects");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  const download = async () => {
    setBusy(true); setError(""); setMessage("");
    try {
      const response = await fetch(`/api/admin/exports?dataset=${encodeURIComponent(dataset)}`, { headers: { Authorization: `Bearer ${session?.access_token || ""}` } });
      if (!response.ok) {
        const body = await response.json().catch(() => ({}));
        throw new Error(body.error || "The export could not be created.");
      }
      const blob = await response.blob();
      const href = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = href;
      link.download = `ecology-${dataset}-export.csv`;
      document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(href);
      setMessage("Export downloaded.");
    } catch (err) { setError(err.message); }
    finally { setBusy(false); }
  };

  const selected = DATASETS.find(([key]) => key === dataset);
  return <section className="export-centre">
    <header className="export-centre__head"><div><span><FileSpreadsheet size={15} /> Operational data exports</span><h2>Export Centre</h2><p>Download live registers for Excel, CSV analysis and Power BI. This area exports operational records only.</p></div><ShieldAlert size={26} /></header>
    <div className="export-centre__notice"><strong>Document boundary</strong><span>REFs, BARs, BDARs, VMPs, Stage 1 Memos, BAM assessments and technical deliverables remain in SharePoint, Teams, OneDrive or the project workspace. They are not generated by this platform.</span></div>
    <div className="export-centre__controls"><label>Register<select value={dataset} onChange={(event) => setDataset(event.target.value)}>{DATASETS.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><button type="button" className="pm-primary" disabled={busy} onClick={download}>{busy ? "Preparing…" : <><Download size={15} /> Download CSV</>}</button></div>
    <div className="export-centre__selected"><strong>{selected?.[1]}</strong><span>{selected?.[2]} Exports are limited to 2,000 rows per download; use filters or scheduled reporting for larger extracts.</span></div>
    {error ? <p className="export-centre__error" role="alert">{error}</p> : null}{message ? <p className="export-centre__success"><CheckCircle2 size={14} /> {message}</p> : null}
    <div className="export-centre__grid">{DATASETS.map(([key, label, description]) => <button type="button" key={key} className={`export-centre__card ${dataset === key ? "selected" : ""}`} onClick={() => setDataset(key)}><FileSpreadsheet size={17} /><strong>{label}</strong><span>{description}</span></button>)}</div>
  </section>;
}
