import { useCallback, useEffect, useState } from "react";
import { ClipboardList, RefreshCw, Search } from "lucide-react";
import { useAuth } from "../lib/AuthProvider";

export default function AdminAuditLog() {
  const { session } = useAuth(); const [records, setRecords] = useState([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(0); const [entityType, setEntityType] = useState(""); const [error, setError] = useState(""); const limit = 25;
  const load = useCallback(async () => { if (!session?.access_token) return; try { setError(""); const params = new URLSearchParams({ page: String(page), limit: String(limit) }); if (entityType.trim()) params.set("entityType", entityType.trim()); const response = await fetch(`/api/admin/audit-log?${params}`, { headers: { Authorization: `Bearer ${session.access_token}` } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Could not load audit history."); setRecords(data.records || []); setTotal(data.total || 0); } catch (err) { setError(err.message); } }, [session?.access_token, page, entityType]);
  useEffect(() => { load(); }, [load]);
  return <section className="audit-log"><header className="audit-log__hero"><div><span><ClipboardList size={15} /> Portal Management · Administrator only</span><h2>Audit log</h2><p>Review recorded edits, approvals, locks, restores, visibility changes and controlled workflow transitions.</p></div><button type="button" onClick={load}><RefreshCw size={15} /> Refresh</button></header><div className="audit-log__filters"><label><Search size={14} /> Entity type<input placeholder="e.g. quote_deliverable" value={entityType} onChange={(e) => { setPage(0); setEntityType(e.target.value); }} /></label><span>{total} record{total === 1 ? "" : "s"}</span></div>{error ? <p className="audit-log__error">{error}</p> : null}<div className="audit-log__table"><table><thead><tr><th>When</th><th>Action</th><th>Entity</th><th>Resource</th><th>Reason</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td>{new Date(record.created_at).toLocaleString("en-AU")}</td><td><b>{record.action}</b></td><td>{record.entity_type}{record.entity_id ? <small>{record.entity_id.slice(0, 8)}</small> : null}</td><td>{record.resource_key || "—"}</td><td>{record.reason || "—"}</td></tr>)}</tbody></table>{!records.length && !error ? <p className="audit-log__empty">No matching audit records yet. New governed changes are recorded as they occur.</p> : null}</div><footer><button type="button" disabled={page === 0} onClick={() => setPage(Math.max(0, page - 1))}>Previous</button><span>Page {page + 1}</span><button type="button" disabled={(page + 1) * limit >= total} onClick={() => setPage(page + 1)}>Next</button></footer></section>;
}
