import { useCallback, useEffect, useState } from "react";
import { Archive, BellRing, CheckCircle2, Link2, Lock, Plus, Unlock } from "lucide-react";
import { useAuth } from "../lib/AuthProvider";

export default function BioNetWatchlistsPanel({ onBack }) {
  const { session } = useAuth(); const [watchlists, setWatchlists] = useState([]); const [events, setEvents] = useState([]); const [form, setForm] = useState({ scientificName: "", commonName: "", profileUrl: "", note: "" }); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const call = useCallback(async (method, body) => { const response = await fetch("/api/bionet-watchlists", { method, headers: { "Content-Type": "application/json", Authorization: `Bearer ${session?.access_token || ""}` }, body: body ? JSON.stringify(body) : undefined }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "BioNet Watch could not be updated."); return data; }, [session?.access_token]);
  const load = useCallback(async () => { if (!session?.access_token) return; try { setError(""); const data = await call("GET"); setWatchlists(data.watchlists || []); setEvents(data.events || []); } catch (err) { setError(err.message); } }, [call, session?.access_token]); useEffect(() => { load(); }, [load]);
  const add = async () => { try { setBusy(true); await call("POST", form); setForm({ scientificName: "", commonName: "", profileUrl: "", note: "" }); await load(); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const act = async (item, action) => { const reason = action === "unlock" ? window.prompt("Unlock reason (recorded in the audit log):") : ""; if (action === "unlock" && !reason) return; try { setBusy(true); await call("PATCH", { id: item.id, action, reason }); await load(); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <section className="bionet-watch"><header><div><span>NSW BioNet · controlled source monitoring</span><h2><BellRing size={19} /> Curated species watchlists</h2><p>Monitor only authoritative, administrator-selected species profiles. Changes create a review item; they never amend species requirements automatically.</p></div><button type="button" onClick={onBack}>Back to profiles</button></header>{error ? <p className="bionet-watch__error">{error}</p> : null}<div className="bionet-watch__add"><input placeholder="Scientific name *" value={form.scientificName} onChange={(e) => setForm({ ...form, scientificName: e.target.value })} /><input placeholder="Common name" value={form.commonName} onChange={(e) => setForm({ ...form, commonName: e.target.value })} /><input placeholder="Official BioNet profile URL *" value={form.profileUrl} onChange={(e) => setForm({ ...form, profileUrl: e.target.value })} /><input placeholder="Review note (optional)" value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} /><button disabled={busy} onClick={add}><Plus size={14} /> Add to watchlist</button></div><div className="bionet-watch__list">{watchlists.map((item) => <article key={item.id}><div><strong>{item.scientific_name}</strong>{item.common_name ? <span>{item.common_name}</span> : null}<small>Last successful check: {item.last_successful_check_at ? new Date(item.last_successful_check_at).toLocaleString("en-AU") : "not yet scanned"}{item.locked ? " · locked" : ""}{!item.active ? " · archived" : ""}</small>{item.profile_url ? <a href={item.profile_url} target="_blank" rel="noreferrer"><Link2 size={12} /> Official source</a> : null}</div><aside>{item.locked ? <button disabled={busy} onClick={() => act(item, "unlock")} title="Unlock"><Unlock size={14} /></button> : <button disabled={busy} onClick={() => act(item, "lock")} title="Lock"><Lock size={14} /></button>}<button disabled={busy} onClick={() => act(item, item.active ? "archive" : "restore")} title={item.active ? "Archive" : "Restore"}><Archive size={14} /></button></aside></article>)}{!watchlists.length ? <p>No individual BioNet profiles are on the watchlist yet.</p> : null}</div><section className="bionet-watch__events"><h3><CheckCircle2 size={16} /> Detected changes awaiting review</h3>{events.filter((event) => event.assessment_status === "detected").map((event) => <p key={event.id}>Detected {new Date(event.detected_at).toLocaleString("en-AU")} · {event.change_summary}</p>)}{!events.some((event) => event.assessment_status === "detected") ? <p>No BioNet profile changes are awaiting assessment.</p> : null}</section></section>;
}
