import { useCallback, useEffect, useState } from "react";
import { BadgeCheck, ClipboardCheck, Clock3, GraduationCap, RotateCcw, Send, ShieldCheck } from "lucide-react";
import { useAuth } from "../lib/AuthProvider";

const label = (status) => String(status || "assigned").replaceAll("_", " ");
export default function LearningAssignmentsPanel({ admin = false }) {
  const { session } = useAuth(); const [assignments, setAssignments] = useState([]); const [staff, setStaff] = useState([]); const [items, setItems] = useState([]); const [nodeId, setNodeId] = useState(""); const [userId, setUserId] = useState(""); const [dueDate, setDueDate] = useState(""); const [note, setNote] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const call = useCallback(async (method, url, body) => { const response = await fetch(url, { method, headers: { "Content-Type": "application/json", Authorization: `Bearer ${session?.access_token || ""}` }, body: body ? JSON.stringify(body) : undefined }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Could not update learning assignment."); return data; }, [session?.access_token]);
  const load = useCallback(async () => { if (!session?.access_token) return; try { setError(""); const data = await call("GET", `/api/learning-assignments${admin ? "" : "?audience=staff"}`); setAssignments(data.assignments || []); setStaff(data.staff || []); setItems(data.items || []); } catch (err) { setError(err.message); } }, [admin, call, session?.access_token]);
  useEffect(() => { load(); }, [load]);
  const assign = async () => { if (!nodeId || !userId) { setError("Choose a learning item and staff member."); return; } try { setBusy(true); await call("POST", "/api/learning-assignments", { nodeId, userId, dueDate, note }); setNodeId(""); setUserId(""); setDueDate(""); setNote(""); await load(); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const act = async (assignmentId, action) => { const actionNote = ["return", "unlock"].includes(action) ? window.prompt("Record a note for this action:") : note; if (["return", "unlock"].includes(action) && !actionNote) return; try { setBusy(true); await call("PATCH", `/api/learning-assignments/${assignmentId}`, { action, note: actionNote }); setNote(""); await load(); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <section className={`learning-assignments ${admin ? "learning-assignments--admin" : ""}`}><header><div><span>{admin ? "Learning governance · Admin" : "Your learning plan"}</span><h2><GraduationCap size={18} /> {admin ? "Assignments & competency" : "Assigned learning"}</h2><p>{admin ? "Assign approved content, assess submissions and verify competency through a recorded workflow." : "Start and submit your assigned learning here. Your reviewer’s feedback and competency status are retained."}</p></div><button type="button" onClick={load}><RotateCcw size={14} /> Refresh</button></header>{error ? <p className="learning-assignments__error">{error}</p> : null}{admin ? <div className="learning-assignments__create"><select value={nodeId} onChange={(e) => setNodeId(e.target.value)}><option value="">Learning item…</option>{items.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><select value={userId} onChange={(e) => setUserId(e.target.value)}><option value="">Staff member…</option>{staff.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select><input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} /><input placeholder="Assignment note (optional)" value={note} onChange={(e) => setNote(e.target.value)} /><button type="button" disabled={busy} onClick={assign}><Send size={14} /> Assign learning</button></div> : null}<div className="learning-assignments__list">{assignments.map((assignment) => <article key={assignment.id}><div><strong>{assignment.ld_nodes?.title || "Learning item"}</strong><small>Due {assignment.due_date || "not set"} · <b className={`learning-assignments__status ${assignment.status}`}>{label(assignment.status)}</b></small>{assignment.remediation_note ? <p>Reviewer note: {assignment.remediation_note}</p> : null}</div><aside>{!admin && assignment.status === "assigned" ? <button disabled={busy} onClick={() => act(assignment.id, "start")}><Clock3 size={14} /> Start</button> : null}{!admin && ["assigned", "started", "returned"].includes(assignment.status) ? <button disabled={busy} onClick={() => act(assignment.id, "submit")}><Send size={14} /> Submit</button> : null}{admin && assignment.status === "submitted" ? <><button disabled={busy} onClick={() => act(assignment.id, "assess")}><ClipboardCheck size={14} /> Assess</button><button disabled={busy} onClick={() => act(assignment.id, "verify")}><BadgeCheck size={14} /> Verify competency</button><button disabled={busy} onClick={() => act(assignment.id, "return")}><RotateCcw size={14} /> Return</button></> : null}{admin && assignment.status === "assessed" ? <button disabled={busy} onClick={() => act(assignment.id, "verify")}><ShieldCheck size={14} /> Verify competency</button> : null}</aside></article>)}{!assignments.length ? <p className="learning-assignments__empty">{admin ? "No learning assignments have been created." : "No learning items are currently assigned to you."}</p> : null}</div></section>;
}
