import { useEffect, useMemo, useState } from "react";
import { Archive, CheckCircle2, FilePlus2, FolderKanban, Lock, Plus, ShieldCheck, Unlock } from "lucide-react";
import { useAuth } from "../lib/AuthProvider";

const blankCategory = { label: "", description: "", sortOrder: 0 };
const blankDeliverable = { title: "", description: "", categoryId: "", estimatedFee: "", estimatedHours: "" };
const call = async (session, method, url, body) => {
  const response = await fetch(url, { method, headers: { "Content-Type": "application/json", Authorization: `Bearer ${session?.access_token || ""}` }, body: body ? JSON.stringify(body) : undefined });
  const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "The update could not be saved."); return data;
};

export default function QuoteGovernanceWorkspace({ quotes, onQuoteChanged }) {
  const { session } = useAuth();
  const [quoteId, setQuoteId] = useState("");
  const [categories, setCategories] = useState([]);
  const [deliverables, setDeliverables] = useState([]);
  const [draftProject, setDraftProject] = useState(null);
  const [category, setCategory] = useState(blankCategory);
  const [deliverable, setDeliverable] = useState(blankDeliverable);
  const [note, setNote] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const activeQuotes = useMemo(() => (quotes || []).filter((quote) => !quote.superseded), [quotes]);
  const selected = activeQuotes.find((quote) => quote.id === quoteId) || null;
  const tell = (text) => { setMessage(text); setError(""); setTimeout(() => setMessage(""), 2800); };
  const loadCategories = async () => { try { const data = await call(session, "GET", "/api/quote-deliverable-categories"); setCategories(data.categories || []); } catch (err) { setError(err.message); } };
  const loadQuote = async (id = quoteId) => { if (!id) { setDeliverables([]); setDraftProject(null); return; } try { const [items, bridge] = await Promise.all([call(session, "GET", `/api/quote-pipeline/${id}/deliverables`), call(session, "GET", `/api/quote-pipeline/${id}/draft-project`)]); setDeliverables(items.deliverables || []); setDraftProject(bridge.draftProject || null); } catch (err) { setError(err.message); } };
  useEffect(() => { if (session?.access_token) loadCategories(); }, [session?.access_token]);
  useEffect(() => { if (session?.access_token) loadQuote(quoteId); }, [quoteId, session?.access_token]);
  const createCategory = async () => { try { setBusy(true); await call(session, "POST", "/api/quote-deliverable-categories", category); setCategory(blankCategory); await loadCategories(); tell("Deliverable category added."); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const categoryAction = async (id, action) => { const reason = action === "unlock" ? window.prompt("Unlock reason (recorded in audit log):") : ""; if (action === "unlock" && !reason) return; try { setBusy(true); await call(session, "PATCH", "/api/quote-deliverable-categories", { id, action, reason }); await loadCategories(); tell(`Category ${action}d.`); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const createDeliverable = async () => { if (!quoteId) { setError("Choose an issued quote first."); return; } try { setBusy(true); await call(session, "POST", `/api/quote-pipeline/${quoteId}/deliverables`, deliverable); setDeliverable(blankDeliverable); await loadQuote(); tell("Quote deliverable added."); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const deliverableAction = async (id, action) => { const reason = action === "unlock" ? window.prompt("Unlock reason (recorded in audit log):") : ""; if (action === "unlock" && !reason) return; try { setBusy(true); await call(session, "PATCH", `/api/quote-pipeline/${quoteId}/deliverables`, { id, action, reason }); await loadQuote(); tell(`Deliverable ${action}d.`); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const bridgeAction = async (action) => { if (!quoteId) return; if (action !== "create" && !note.trim()) { setError("Record the decision note before changing draft-project status."); return; } try { setBusy(true); const data = await call(session, "POST", `/api/quote-pipeline/${quoteId}/draft-project`, { action, note }); setDraftProject(data.draftProject || null); setNote(""); onQuoteChanged?.(); tell(action === "create" ? "Draft project created for review." : `Draft project ${action}d.`); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <section className="quote-governance"><header className="quote-governance__hero"><span><ShieldCheck size={15} /> Commercial governance · Admin</span><h1>Deliverables & Draft Project Approval</h1><p>Manage reusable deliverable categories, add scoped quote line items, and create one review-gated draft project from a successful quote. Activation is never automatic.</p></header>
    {error ? <p className="quote-governance__error">{error}</p> : null}{message ? <p className="quote-governance__success"><CheckCircle2 size={14} /> {message}</p> : null}
    <div className="quote-governance__grid"><article className="quote-governance__card"><h2>Deliverable categories</h2><p>Categories can be locked or archived; used records are retained.</p><div className="quote-governance__form"><input placeholder="Category name" value={category.label} onChange={(e) => setCategory({ ...category, label: e.target.value })} /><input placeholder="Description" value={category.description} onChange={(e) => setCategory({ ...category, description: e.target.value })} /><button type="button" disabled={busy} onClick={createCategory}><Plus size={14} /> Add category</button></div><div className="quote-governance__list">{categories.map((row) => <div key={row.id}><span><strong>{row.label}</strong><small>{row.active ? "active" : "archived"}{row.locked ? " · locked" : ""}</small></span><aside>{row.locked ? <button type="button" title="Unlock with a reason" onClick={() => categoryAction(row.id, "unlock")}><Unlock size={14} /></button> : <button type="button" title="Lock category" onClick={() => categoryAction(row.id, "lock")}><Lock size={14} /></button>}<button type="button" title={row.active ? "Archive category" : "Restore category"} onClick={() => categoryAction(row.id, row.active ? "archive" : "restore")}><Archive size={14} /></button></aside></div>)}{!categories.length ? <p>No categories yet.</p> : null}</div></article>
      <article className="quote-governance__card"><h2>Quote deliverables</h2><label>Issued quote<select value={quoteId} onChange={(e) => setQuoteId(e.target.value)}><option value="">Choose a quote…</option>{activeQuotes.map((quote) => <option key={quote.id} value={quote.id}>{quote.client || "Client"} · {quote.project || "Untitled project"} · {quote.status}</option>)}</select></label>{selected ? <p className="quote-governance__selected">{selected.client || "Client"} · {selected.project || "Project"}</p> : null}<div className="quote-governance__form"><input placeholder="Deliverable title" value={deliverable.title} onChange={(e) => setDeliverable({ ...deliverable, title: e.target.value })} /><select value={deliverable.categoryId} onChange={(e) => setDeliverable({ ...deliverable, categoryId: e.target.value })}><option value="">Category (optional)</option>{categories.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><input placeholder="Estimated hours" type="number" min="0" value={deliverable.estimatedHours} onChange={(e) => setDeliverable({ ...deliverable, estimatedHours: e.target.value })} /><input placeholder="Estimated fee" type="number" min="0" value={deliverable.estimatedFee} onChange={(e) => setDeliverable({ ...deliverable, estimatedFee: e.target.value })} /><input placeholder="Description / assumptions" value={deliverable.description} onChange={(e) => setDeliverable({ ...deliverable, description: e.target.value })} /><button type="button" disabled={!quoteId || busy} onClick={createDeliverable}><FilePlus2 size={14} /> Add deliverable</button></div><div className="quote-governance__list">{deliverables.map((row) => <div key={row.id}><span><strong>{row.title}</strong><small>{row.quote_deliverable_categories?.label || "Uncategorised"} · {row.estimated_hours ?? "—"} h · {row.status}{row.locked ? " · locked" : ""}</small></span><aside>{row.locked ? <button type="button" title="Unlock with a reason" onClick={() => deliverableAction(row.id, "unlock")}><Unlock size={14} /></button> : <button type="button" title="Lock deliverable" onClick={() => deliverableAction(row.id, "lock")}><Lock size={14} /></button>}<button type="button" title={row.status === "archived" ? "Restore deliverable" : "Archive deliverable"} onClick={() => deliverableAction(row.id, row.status === "archived" ? "restore" : "archive")}><Archive size={14} /></button></aside></div>)}{quoteId && !deliverables.length ? <p>No deliverables recorded for this quote.</p> : null}</div></article></div>
    <article className="quote-governance__card quote-governance__bridge"><h2><FolderKanban size={18} /> Draft project approval bridge</h2><p>A successful, non-superseded quote can create one draft project. It must be approved before activation and all decisions are recorded in the audit log.</p>{draftProject ? <div className="quote-governance__bridge-state"><strong>{draftProject.projects?.name || "Draft project"}</strong><span>Status: {draftProject.status.replaceAll("_", " ")}</span></div> : null}<label>Review / decision note<textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="Record why the draft project is approved, rejected or activated." /></label><div className="quote-governance__actions"><button type="button" disabled={!quoteId || busy || selected?.status !== "successful"} onClick={() => bridgeAction("create")}>Create draft project</button><button type="button" disabled={!draftProject || busy || draftProject.status !== "pending_review"} onClick={() => bridgeAction("approve")}>Approve</button><button type="button" disabled={!draftProject || busy || !["pending_review", "approved"].includes(draftProject.status)} onClick={() => bridgeAction("reject")}>Reject</button><button type="button" disabled={!draftProject || busy || draftProject.status !== "approved"} onClick={() => bridgeAction("activate")}>Activate project</button></div></article>
  </section>;
}
