import { createClient } from "@supabase/supabase-js";
import { createHash } from "node:crypto";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
const normalise = (value) => String(value || "").replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim().slice(0, 750000);
const checksum = (value) => createHash("sha256").update(value).digest("hex");
const authorised = (request) => Boolean(process.env.CRON_SECRET) && request.headers.get("authorization") === `Bearer ${process.env.CRON_SECRET}`;
const adminClient = () => { if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) throw new Error("BioNet watch requires Supabase server credentials."); return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } }); };
async function notifyAdmins(admin, event, name) { try { const [{ data: users }, { data: emailRows }] = await Promise.all([admin.auth.admin.listUsers({ page: 1, perPage: 1000 }), admin.from("admin_emails").select("email")]); const emails = new Set((emailRows || []).map((row) => String(row.email || "").toLowerCase())); const recipients = (users?.users || []).filter((user) => emails.has(String(user.email || "").toLowerCase())); if (recipients.length) await admin.from("portal_events").insert(recipients.map((user) => ({ recipient_id: user.id, event_type: "bionet_watch_change", severity: "review", title: `BioNet review required: ${name}`, body: "A curated BioNet profile changed. An authorised ecologist must review the source, assess operational impact and decide whether requirements, survey methods, training or projects need amendment.", href: "/?portal=admin&area=species", source_table: "bionet_watch_events", source_id: event.id }))); } catch (error) { console.error("BioNet watch notification failed", error); } }
export async function GET(request) {
  if (!authorised(request)) return Response.json({ error: "Unauthorised scheduler." }, { status: 401 });
  try { const admin = adminClient(); const { data: watchlists, error } = await admin.from("bionet_watchlists").select("id, scientific_name, common_name, profile_url, locked, last_observed_checksum").eq("active", true).order("scientific_name"); if (error) throw new Error(error.message); const results = [];
    for (const item of watchlists || []) { const checkedAt = new Date().toISOString(); try { const response = await fetch(item.profile_url, { headers: { "User-Agent": "EcologyConsulting-BioNetWatch/1.0 (ecology review monitor)" }, redirect: "follow", signal: AbortSignal.timeout(20000) }); const raw = await response.text(); if (!response.ok) throw new Error(`HTTP ${response.status}`); const observed = checksum(normalise(raw)); const changed = Boolean(item.last_observed_checksum && item.last_observed_checksum !== observed); if (changed) { const { data: event, error: eventError } = await admin.from("bionet_watch_events").insert({ watchlist_id: item.id, source_url: item.profile_url, snapshot_hash: observed, change_summary: "The selected official BioNet profile differs from its previous successful observation.", assessment_status: "detected" }).select("id").single(); if (eventError) throw new Error(eventError.message); await notifyAdmins(admin, event, item.scientific_name); }
      await admin.from("bionet_watchlists").update({ last_observed_checksum: observed, last_checked_at: checkedAt, last_successful_check_at: checkedAt, updated_at: checkedAt }).eq("id", item.id); results.push({ id: item.id, scientific_name: item.scientific_name, ok: true, changed });
    } catch (error) { await admin.from("bionet_watchlists").update({ last_checked_at: checkedAt, updated_at: checkedAt }).eq("id", item.id); results.push({ id: item.id, scientific_name: item.scientific_name, ok: false, error: String(error.message || "Profile check failed") }); } }
    return Response.json({ ok: true, checked_at: new Date().toISOString(), results });
  } catch (error) { return Response.json({ error: error.message || "BioNet watch failed." }, { status: 500 }); }
}
