import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const root = new URL("..", import.meta.url);
const read = (path) => readFile(new URL(path, root), "utf8");
const catalogue = JSON.parse(await read("data/core-training/quizzes.public.json"));
const keys = JSON.parse(await read("lib/server/coreTrainingQuizKeys.json"));
const endpoint = await read("app/api/core-training-quizzes/route.js");
const runner = await read("components/CoreTrainingQuizzes.js");
const learning = await read("components/StaffLearningLibrary.js");
const requests = await read("components/StaffServiceRequests.js");
const staffList = await read("components/PortalStaffList.js");
const management = await read("components/PortalManagement.js");

assert.equal(catalogue.length, 41, "Expected 41 fully marked Core Training quizzes.");
assert.ok(catalogue.every((quiz) => quiz.questions.length === quiz.questionCount), "Every published quiz must have a complete question set.");
const m09 = catalogue.find((quiz) => quiz.quizId === "core-m09");
assert.deepEqual(m09 && { questionCount: m09.questionCount, passMark: m09.threshold.passMark, outOf: m09.threshold.outOf }, { questionCount: 50, passMark: 32, outOf: 50 }, "M09 must use its supplied 50-question marker key and 32/50 threshold.");
assert.ok(catalogue.every((quiz) => quiz.questions.every((question) => question.prompt && question.options.length === 4 && question.options.every((option) => option.text))), "Every question must have four populated choices.");
assert.ok(catalogue.every((quiz) => !Object.hasOwn(quiz, "answers")), "The public question catalogue must not include answer keys.");
assert.ok(catalogue.every((quiz) => Object.keys(keys[quiz.quizId]?.answers || {}).length === quiz.questionCount), "Every published quiz must have a complete server-only answer key.");
const allQuestions = catalogue.flatMap((quiz) => quiz.questions.map((question) => ({ quiz, question })));
assert.ok(allQuestions.every(({ question }) => !/which proposed response should be rejected first\?/i.test(question.prompt)), "Questions must ask staff to identify the defensible response, not invert the protected answer key.");
const normalise = (value) => String(value || "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const answerSet = (question) => question.options.map((option) => normalise(option.text)).sort().join(" | ");
assert.equal(new Set(allQuestions.map(({ question }) => normalise(question.prompt))).size, allQuestions.length, "Every published Core Training prompt must be unique across all modules.");
assert.equal(new Set(allQuestions.map(({ question }) => answerSet(question))).size, allQuestions.length, "Each question must have its own module-specific answer set rather than a shared answer template.");
assert.ok(allQuestions.every(({ question }) => question.options.map((option) => option.key).sort().join("") === "ABCD"), "Every question must expose one substantive choice for each A–D key.");
assert.ok(allQuestions.every(({ question }) => new Set(question.options.map((option) => normalise(option.text))).size === 4), "Each question must have four different option texts.");
assert.ok(allQuestions.every(({ quiz, question }) => question.options.some((option) => option.key === keys[quiz.quizId]?.answers?.[String(question.number)])), "Every protected answer must map to a visible option for that question.");
assert.ok(catalogue.every((quiz) => Object.keys(keys[quiz.quizId]?.rationales || {}).length === quiz.questionCount), "Every protected answer must include a rationale.");
assert.equal(new Set(catalogue.flatMap((quiz) => Object.values(keys[quiz.quizId]?.rationales || {}).map(normalise))).size, allQuestions.length, "Rationales must be question-specific rather than copied across a module.");
assert.ok(catalogue.every((quiz) => new Set(Object.values(keys[quiz.quizId]?.answers || {})).size === 4), "Each module must distribute correct answers across all four option positions.");
assert.ok(!allQuestions.some(({ question }) => /current controlled source and allocation.*nominated supervisor/i.test(question.options.map((option) => option.text).join(" "))), "The retired generic organisational-control answer template must not reappear in module assessments.");
assert.match(endpoint, /requirePortalResource\(access, "staff\.learning"\)/, "Learning visibility must be enforced server-side.");
assert.match(endpoint, /export async function PATCH/, "The quiz endpoint must expose draft autosave.");
assert.match(endpoint, /export async function POST/, "The quiz endpoint must expose explicit server-side marking.");
assert.match(endpoint, /core_training_quiz_drafts/, "Quiz autosave must use the protected draft store.");
assert.match(runner, /Submit and receive feedback/, "The runner must make marking an explicit action.");
assert.match(runner, /not the response that should be rejected/, "The runner must tell staff that every question asks for the defensible response.");
assert.match(runner, /most defensible response:/, "Incorrect-answer feedback must describe the highlighted key as the most defensible response.");
assert.match(runner, /window\.localStorage\.setItem\(draftKey/, "The runner must retain answers locally when the network is unavailable.");
assert.match(learning, /CoreTrainingQuizzes/, "The Core Training learning folder must open the quiz workspace.");
assert.match(requests, /ec-service-request-draft/, "Unsubmitted Service Requests must autosave locally per staff account.");
assert.match(staffList, /Add staff member/, "Staff List must expose the requested creation action.");
assert.match(management, /onAddStaff/, "The Staff List action must open controlled account creation.");
console.log(`Core Training contract passed: ${catalogue.length} interactive quizzes and all autosave/access safeguards verified.`);
