import { requireSession, serverError } from "../../../lib/serverAuth";
import { requirePortalResource } from "../../../lib/portalVisibility";
import { compactAuditRecord, recordAudit } from "../../../lib/auditLog";

const WATCH_COLUMNS = "id, scientific_name, common_name, profile_url, jurisdiction, active, locked, last_observed_checksum, last_checked_at, last_successful_check_at, review_note, reviewed_by, reviewed_at, created_by, created_at, updated_at";
const EVENT_COLUMNS = "id, watchlist_id, detected_at, source_url, snapshot_hash, change_summary, assessment_status, assessed_by, assessed_at, assessment_note, created_at";
const text = (value, maximum = 2000) => { const clean = String(value || "").trim(); return clean ? clean.slice(0, maximum) : null; };

async function allowed(access) { if (!access.isAdmin) return Response.json({ error: "Administrators only." }, { status: 403 }); return requirePortalResource(access, "admin.species.bionet_watchlists"); }
export async function GET(request) { try { const access = await requireSession(request); if (access.error) return access.error; const denied = await allowed(access); if (denied) return denied; const [watchResult, eventResult] = await Promise.all([access.admin.from("bionet_watchlists").select(WATCH_COLUMNS).order("active", { ascending: false }).order("scientific_name"), access.admin.from("bionet_watch_events").select(EVENT_COLUMNS).order("detected_at", { ascending: false }).limit(150)]); if (watchResult.error) return Response.json({ error: watchResult.error.message }, { status: 400 }); if (eventResult.error) return Response.json({ error: eventResult.error.message }, { status: 400 }); return Response.json({ watchlists: watchResult.data || [], events: eventResult.data || [] }); } catch (error) { return serverError(error); } }
export async function POST(request) { try { const access = await requireSession(request); if (access.error) return access.error; const denied = await allowed(access); if (denied) return denied; const body = await request.json(); const scientificName = text(body.scientificName, 220); const profileUrl = text(body.profileUrl, 2000); if (!scientificName || !profileUrl) return Response.json({ error: "Scientific name and official BioNet profile URL are required." }, { status: 400 }); if (!/^https:\/\/(threatenedspecies\.bionet\.nsw\.gov\.au|www\.environment\.nsw\.gov\.au)\//.test(profileUrl)) return Response.json({ error: "Use an official NSW BioNet or Environment URL." }, { status: 400 }); const { data, error } = await access.admin.from("bionet_watchlists").insert({ scientific_name: scientificName, common_name: text(body.commonName, 220), profile_url: profileUrl, jurisdiction: "NSW", review_note: text(body.note), created_by: access.user.id }).select(WATCH_COLUMNS).single(); if (error) return Response.json({ error: error.code === "23505" ? "This species is already on the NSW watchlist." : error.message }, { status: 400 }); await recordAudit(access.admin, { actorId: access.user.id, action: "created", entityType: "bionet_watchlist", entityId: data.id, resourceKey: "admin.species.bionet_watchlists", afterData: compactAuditRecord(data, ["scientific_name", "profile_url", "active", "locked"]), reason: text(body.note) }); return Response.json({ watchlist: data }, { status: 201 }); } catch (error) { return serverError(error); } }
export async function PATCH(request) { try { const access = await requireSession(request); if (access.error) return access.error; const denied = await allowed(access); if (denied) return denied; const body = await request.json();
  if (body.eventId) {
    const status = ["reviewed", "actioned", "ignored", "archived"].includes(body.status) ? body.status : null;
    if (!status) return Response.json({ error: "Choose a valid BioNet event assessment status." }, { status: 400 });
    const { data: event, error: readError } = await access.admin.from("bionet_watch_events").select(EVENT_COLUMNS).eq("id", body.eventId).single();
    if (readError) return Response.json({ error: "BioNet change event not found." }, { status: 404 });
    const { data, error } = await access.admin.from("bionet_watch_events").update({ assessment_status: status, assessed_by: access.user.id, assessed_at: new Date().toISOString(), assessment_note: text(body.note, 4000) }).eq("id", event.id).select(EVENT_COLUMNS).single();
    if (error) return Response.json({ error: error.message }, { status: 400 });
    await recordAudit(access.admin, { actorId: access.user.id, action: status, entityType: "bionet_watch_event", entityId: data.id, resourceKey: "admin.species.bionet_watchlists", beforeData: compactAuditRecord(event, ["assessment_status"]), afterData: compactAuditRecord(data, ["assessment_status"]), reason: text(body.note, 4000) });
    return Response.json({ event: data });
  }
  if (!body.id) return Response.json({ error: "Choose a watchlist entry." }, { status: 400 }); const { data: current, error: readError } = await access.admin.from("bionet_watchlists").select(WATCH_COLUMNS).eq("id", body.id).single(); if (readError) return Response.json({ error: "Watchlist entry not found." }, { status: 404 }); if (current.locked && body.action !== "unlock") return Response.json({ error: "This watchlist entry is locked. Unlock it with a reason before editing." }, { status: 409 }); const values = { updated_at: new Date().toISOString() }; if ("scientificName" in body) values.scientific_name = text(body.scientificName, 220) || current.scientific_name; if ("commonName" in body) values.common_name = text(body.commonName, 220); if ("profileUrl" in body) values.profile_url = text(body.profileUrl, 2000) || current.profile_url; if (body.action === "lock") values.locked = true; if (body.action === "unlock") { if (!text(body.reason, 1000)) return Response.json({ error: "Provide an unlock reason." }, { status: 400 }); values.locked = false; } if (body.action === "archive") values.active = false; if (body.action === "restore") values.active = true; const { data, error } = await access.admin.from("bionet_watchlists").update(values).eq("id", current.id).select(WATCH_COLUMNS).single(); if (error) return Response.json({ error: error.message }, { status: 400 }); await recordAudit(access.admin, { actorId: access.user.id, action: body.action || "updated", entityType: "bionet_watchlist", entityId: data.id, resourceKey: "admin.species.bionet_watchlists", beforeData: compactAuditRecord(current, ["scientific_name", "active", "locked"]), afterData: compactAuditRecord(data, ["scientific_name", "active", "locked"]), reason: text(body.reason, 1000) }); return Response.json({ watchlist: data }); } catch (error) { return serverError(error); } }
